// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/create": {
            "post": {
                "description": "ทดสอบสร้าง User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "JSON Body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userModel.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "put": {
                "description": "ทดสอบ Update User ด้วย Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User By Id",
                "parameters": [
                    {
                        "description": "JSON Body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userModel.UserUpdate"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID ของผู้ใช้",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    },
                    "4010": {
                        "description": "HTTP Code 200, ไม่มีการ Authorization ",
                        "schema": {
                            "$ref": "#/definitions/helper.UnAuthorizeResponse"
                        }
                    },
                    "4040": {
                        "description": "HTTP Code 200, ไม่พบข้อมูล",
                        "schema": {
                            "$ref": "#/definitions/helper.NotFoundResponse"
                        }
                    },
                    "5000": {
                        "description": "HTTP Code 500, ข้อผิดพลาดภายในเซิร์ฟเวอร์",
                        "schema": {
                            "$ref": "#/definitions/helper.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "ทดสอบ get",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page ที่",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit ที่",
                        "name": "row",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort ex: firstname desc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ต้องการหาชื่ออะไร",
                        "name": "firstname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "นามสกุลที่ต้องการหา",
                        "name": "lastname",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "ทดสอบ Update User หลายคนพร้อมกัน",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Multiple User",
                "parameters": [
                    {
                        "description": "JSON Body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/userModel.User"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    },
                    "4010": {
                        "description": "HTTP Code 200, ไม่มีการ Authorization ",
                        "schema": {
                            "$ref": "#/definitions/helper.UnAuthorizeResponse"
                        }
                    },
                    "4040": {
                        "description": "HTTP Code 200, ไม่พบข้อมูล",
                        "schema": {
                            "$ref": "#/definitions/helper.NotFoundResponse"
                        }
                    },
                    "5000": {
                        "description": "HTTP Code 500, ข้อผิดพลาดภายในเซิร์ฟเวอร์",
                        "schema": {
                            "$ref": "#/definitions/helper.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/create": {
            "post": {
                "description": "ทดสอบสร้าง User แบบหลายคนพร้อมกัน",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create Multiple Users",
                "parameters": [
                    {
                        "description": "JSON Body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/userModel.User"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/users/delete": {
            "delete": {
                "description": "ทดสอบ Delete User หลายคนพร้อมกัน",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Soft Delete Multiple Users",
                "parameters": [
                    {
                        "description": "JSON Body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/userModel.User"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    },
                    "4010": {
                        "description": "HTTP Code 200, ไม่มีการ Authorization ",
                        "schema": {
                            "$ref": "#/definitions/helper.UnAuthorizeResponse"
                        }
                    },
                    "4040": {
                        "description": "HTTP Code 200, ไม่พบข้อมูล",
                        "schema": {
                            "$ref": "#/definitions/helper.NotFoundResponse"
                        }
                    },
                    "5000": {
                        "description": "HTTP Code 500, ข้อผิดพลาดภายในเซิร์ฟเวอร์",
                        "schema": {
                            "$ref": "#/definitions/helper.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/products/order": {
            "get": {
                "description": "ทดสอบ get user order detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Order Detail",
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "description": "ทดสอบ Delete User ด้วย Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Soft Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ของผู้ใช้",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTTP Code 200, สร้างสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/helper.SuccessResponse"
                        }
                    },
                    "4010": {
                        "description": "HTTP Code 200, ไม่มีการ Authorization ",
                        "schema": {
                            "$ref": "#/definitions/helper.UnAuthorizeResponse"
                        }
                    },
                    "4040": {
                        "description": "HTTP Code 200, ไม่พบข้อมูล",
                        "schema": {
                            "$ref": "#/definitions/helper.NotFoundResponse"
                        }
                    },
                    "5000": {
                        "description": "HTTP Code 500, ข้อผิดพลาดภายในเซิร์ฟเวอร์",
                        "schema": {
                            "$ref": "#/definitions/helper.InternalServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 5000
                },
                "message": {
                    "type": "string",
                    "example": "INTERNAL SERVER ERROR"
                }
            }
        },
        "helper.NotFoundResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 4040
                },
                "message": {
                    "type": "string",
                    "example": "NOT FOUND"
                }
            }
        },
        "helper.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Response Code",
                    "type": "integer",
                    "example": 2000
                },
                "message": {
                    "description": "Response Status",
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "helper.UnAuthorizeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 4010
                },
                "message": {
                    "type": "string",
                    "example": "UNAUTHORIZED"
                }
            }
        },
        "userModel.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "userModel.UserUpdate": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Assignment 1",
	Description:      "This is a sample server assignment 1 Internships.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
